FROM node:6

RUN useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app
WORKDIR $HOME/src

COPY .babelrc .eslintrc.json package.json npm-shrinkwrap.json webpack.config.js ./
RUN npm install --ignore-scripts
COPY ./src ./src
COPY ./test ./test

CMD npm test
