version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - BUILD_TAG=$(date +%Y-%m-%d.%H%M%S%3N)-$HASH
      - npm install
      - PACKAGE_FILE=tf-github-webhooks-$BUILD_TAG.zip
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mv dist/tf-github-webhooks.zip dist/$PACKAGE_FILE
      - ./publish-lambda.sh