version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - BUILD_TAG=$(date +%Y-%m-%d.%H%M%S%3N)-$HASH
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "dist/tf-github-webhooks.zip"
  name: tf-github-webhooks-$BUILD_TAG.zip