version: '3.5'
services:
  tf-github-webhooks:
    build:
      context: .
      dockerfile: ./test/Dockerfile.test
    command: npm run coverage
    environment:
      CONFIG_PARAMETER_NAMES: foo,bar
      #DEBUG: app-container*
      GITHUB_SECRET: SECRET
      LOG_LEVEL: fatal
      NODE_ENV: test
      SNS_TOPIC_ARN: 'abcdefg'
    volumes:
      - ./:/home/app
      - /home/app/node_modules